language:
  - node_js
node_js:
  - "12.18.3"
cashe:
  directories:
    - node_modules

# whitelist
branches:
  only:
    - master

before_deploy:
  - npm run build
  - echo -e "node_modules\npackage-lock.json" > .gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master


